spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/customers
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog.xml
    default-schema: public
